version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/hms-front
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
hooks:
  #ApplicationStop:
  BeforeInstall:
    - location: scripts/application-stop.sh
      timeout: 120
      runas: ubuntu
  #  - location: scripts/install_security.sh
  #    timeout: 300
  #    runas: root
    - location: scripts/install-dependencies.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 120
      runas: ubuntu
  #ValidateService:
  #  - location: scripts/validate.sh
  #    timeout: 60
  #    runas: ubuntu