version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
      - pip install awscli --upgrade --user
      - npm install -g chalk
      # https://stackoverflow.com/questions/46584324/code-build-continues-after-build-fails
      # Codebuild's post_build always run regardless of build's success or failure!
      - echo '#!/bin/bash' > /usr/local/bin/ok; echo 'if [[ "$CODEBUILD_BUILD_SUCCEEDING" == "0" ]]; then exit 1; else exit 0; fi' >> /usr/local/bin/ok; chmod +x /usr/local/bin/ok
  pre_build:
    commands:
      - npm cache clean --force
      - npm install
  build:
    commands:
      - npm run build
      # - command
  post_build:
    commands:
      - ok && echo Build completed on `date`
      - ls -l ./public
      - aws s3 sync --cache-control max-age=86400 --exclude=index.html ./public/ s3://live-tour-front-web/hms-front-web/mobile
      - aws s3 sync --cache-control max-age=0  --include=index.html ./public/ s3://live-tour-front-web/hms-front-web/mobile
#artifacts:
  #files:
    # - location
    # - location
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
